### ISSUE TITLE
Not show metrics and mappings with 2.0.4

### ISSUE THREAD

**Issue by raulvillalbamedina** [codecentric/spring-boot-admin#1045]
We have apps with Springboot2 2.0.6.RELEASE and spring-boot-admin 2.0.4.
When i check the metrics or mappings only show this message "Metrics are not supported for Spring Boot 1.x applications. "

I do not find the solution.

Thank you

![metricsfailure](https://user-images.githubusercontent.com/818372/50343152-2938df80-0526-11e9-9b61-ad5c50a7458f.png)

**Comment by joshiste** [comment]
There is no solution other than upgrading your client services. From Spring Boot 1.x to 2.x the metrics endpoint was massively changed so that an easy conversion for the metrics is not possible.

**Comment by TobiasMende** [comment]
I had the same issue with a Spring Boot 2.1.3 application using Spring Boot Admin 2.1.3 and I found the reason (and a solution):

After digging a little bit in the Spring Boot Admin code, I found the reason in `index.vue`: The decision if the endpoints are Spring Boot 2 Actuator endpoints or not is made based on the content-type of the responses from the Spring Boot application.

If the content type is `application/vnd.spring-boot.actuator.v2`, the application is considered to be a Spring Boot 2 application. Otherwise not. In my case, our application had a `WebMvcConfigurer` which set the `defaultContentType` to `application/json`. After adding `MediaType.valueOf("application/vnd.spring-boot.actuator.v2")` to this (at the first place), Spring Boot Admin showed me the metrics.

I hope, this helps. :-)

**Comment by raulvillalbamedina** [comment]
With some of my apps this change works!. Now I review if i use other WebMvcConfigurer or similar in my actual bad apps. Thank you

Please @joshiste  review this problem

**Comment by raulvillalbamedina** [comment]
ok i found the difference, in the apps where is not working i use this "CorsConfig"

Adding the @TobiasMende solution is equal, not working. Some idea?

> 
@RefreshScope
@Configuration
@EnableWebMvc
public class CorsConfig {

    @Bean
    public WebMvcConfigurer corsConfigurer() {
        return new WebMvcConfigurer() {

            @Override
            public void addCorsMappings(CorsRegistry registry) {
                registry.addMapping("/**").allowedOrigins("*").allowedMethods("*").allowedMethods("*");
            }

            @Override
            public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
                configurer.favorPathExtension(false).favorParameter(true).parameterName("mediaType").ignoreAcceptHeader(true).useRegisteredExtensionsOnly(
                        false).defaultContentType(MediaType.APPLICATION_JSON).mediaType("json", MediaType.valueOf(
                                "application/vnd.spring-boot.actuator.v2")).mediaType("json", MediaType.APPLICATION_JSON);
            }
        };
    }
}

>

**Comment by TobiasMende** [comment]
Hi @raulvillalbamedina , in my application, I had to add the Actuator Content Type to the `defaultContentType`. I have tried to add it to the `mediaType` only, which had also no effect.

```
@Bean
public WebMvcConfigurer corsConfigurer() {
    return new WebMvcConfigurer() {

        @Override
        public void addCorsMappings(CorsRegistry registry) {
            registry.addMapping("/**").allowedOrigins("*").allowedMethods("*").allowedMethods("*");
        }

        @Override
        public void configureContentNegotiation(ContentNegotiationConfigurer configurer) {
            configurer.favorPathExtension(false).favorParameter(true).parameterName("mediaType").ignoreAcceptHeader(true).useRegisteredExtensionsOnly(
                    false).defaultContentType(MediaType.valueOf(
                            "application/vnd.spring-boot.actuator.v2"), MediaType.APPLICATION_JSON).mediaType("json", MediaType.APPLICATION_JSON);
        }
    };
}
```
