### ISSUE TITLE
Upgrade to Spring Cloud Greenwich

### ISSUE THREAD

**Issue by riba2101** [codecentric/spring-boot-admin#1052]
SBA spring dependency was updated to 2.1.1, but the cloud dependency was left on Finchley.

It should be on Greenwich

**Comment by sycz** [comment]
I have encountered the same problem, version conflict is a troublesome issue.

[https://spring.io/projects/spring-cloud#overview](url)

**Cloud Version** &nbsp; |  &nbsp;&nbsp;   **Boot Version**
Greenwich     &nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;  |   &nbsp;&nbsp;  2.1.x
Finchley   &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; |  &nbsp;&nbsp;   2.0.x

**the SBA historical version 2.1.0 depends on the following :** 

<spring-boot-admin.version>2.1.0</spring-boot-admin.version>
<spring-boot.version>2.1.0.RELEASE</spring-boot.version>
<spring-cloud.version>Finchley.SR2</spring-cloud.version>

It will cause some exception **eg:** java.lang.NoClassDefFoundError,
because some package structure adjustment.

**Comment by joshiste** [comment]
With ce7f3daf995e0f7cf459fdff88cbdd4c3625c3e1 the master branch is now on Greenwich.RC2 you can try one of the snapshot builds.
I'll resolve this issue after Greenwich.RELEASE is available
