### ISSUE TITLE
json-simple library missing in war-file

### ISSUE THREAD

**Issue by librucha** [codecentric/spring-boot-admin#114]
json-simple library which is dependency of jolokia-core which is dependency spring-boot-admin-starter-client is defined in spring-boot-dependencies as optional dependency.
When I build application, this jar is not included in final war. Solution is implicit definition in some pom.xml but I think it should be defined in spring-boot-admin-starter-client pom.xml

**Comment by joshiste** [comment]
I another solution is to remove the jolokia-core dependency from spring-boot-admin-client. The client itself doesn't need jolokia. It is needed on the for the JMX and Logging pages to work correctly. But for those who don't use the client but discovery have to include jolokia themselves at the moment.

**Comment by joshiste** [comment]
This only seems to be a problem using packaging war....

**Comment by joshiste** [comment]
Are you using the spring-boot-parent for your war-file or the spring-boot-dependencies import? 
If yes, it won't help adding the dependency once more in spring-boot-admin-starter-client/pom.xml because the dependencyManagement of your pom.xml  (from boot-parent or bom-import) will mark it as optional - and therefore json-simple won't be included in your war. 
As a workaround you can use the spring-boot-maven-plugin and build a fat-jar. The boot-packager will include json-simple into the war.

So I'm closing this issue, since it is related to the war-packaging and not too spring-boot-admin.

**Comment by ahirsh** [comment]
Hi,
i have came across this issue when using inheriting from spring boot parent and i got to this thread,
my problem is that:
[1] when packaging war with maven 3.0.4 i get the json-simple inside war -- this is OK.
[2] when packaging with maven 3.3.x war i dont have this jar in my war file --this is not OK.

I'm using ProjectX-->(Inherit)Spring-boot-Parent  and also declare a dependency Y that has dependency for json-simple. 
do you know why i get different outputs with the different versions of maven ? 

(I understnad it is marked as optional but i'm left with 2 questions: 
[1] why is the different results with different maven versions ? 
[2] if i have ProjectX-->(Inherit)Spring-boot-Parent  and also declare a dependency Y that has dependency for json-simple, shouldnt the dependency for simple-json be transitive into war and recognize that ? 

thanks (if im not in the right forum to ask this question i will be happy to be forwarded to the right place).
