### ISSUE TITLE
Custom interceptors for http requests made by the UI

### ISSUE THREAD

**Issue by ezraroi** [codecentric/spring-boot-admin#1174]
We need to make a login call to a auth service from the client and store the JWT token in the client and add it to every request made by the client code.

The auth service is doing kerberos auth so it is not possible to do it in the server side.
In version 1 of boot admin we added angular interceptor to do this, is it possible to do it also in version 2?

**Comment by joshiste** [comment]
Currently there is no feasible solution to add your own axios interceptors.
Imho it would be easier if you'd transmit the token via a cookie. As it would be added right away to the requests.
If you still need a customizing option, I'm happy to accept a PR on this topic, as I'm currently having very limited time. 
The easiest thing todo would be to pass along the axios instance into the install callback used by custom extensions (see https://codecentric.github.io/spring-boot-admin/current/#customizing-custom-views-top-level) so that it can be customized.

**Comment by ezraroi** [comment]
@joshiste  will do so! this was my original idea
