### ISSUE TITLE
io.netty.channel.ConnectTimeoutException: connection timed out: host.docker.internal/192.168.20.180:8080

### ISSUE THREAD

**Issue by archine** [codecentric/spring-boot-admin#1257]
Couldn't retrieve status for Instance(id=34fecff80a31, version=0, registration=Registration(name=UNKNOWN, managementUrl=http://host.docker.internal:8080/actuator, healthUrl=http://host.docker.internal:8080/actuator/health, serviceUrl=http://host.docker.internal:8080/, source=discovery), registered=true, statusInfo=StatusInfo(status=UNKNOWN, details={}), statusTimestamp=2019-09-12T01:22:32.905Z, info=Info(values={}), endpoints=Endpoints(endpoints={health=Endpoint(id=health, url=http://host.docker.internal:8080/actuator/health)}), buildVersion=null, tags=Tags(values={}))

**Comment by archine** [comment]
Using the SpringCloud environment, the admin server starts with this exception

**Comment by joshiste** [comment]
The admin server tries to check the health for a application running on host `host.docker.internal` 
 and port `8080` and this fails because there is no service listening on the port / the host can't be resolved.

First please check if the registered url for the instance is correct. If you are using SBA client you can override the guessed url using `spring.boot.admin.client.instance.service-base-url=http://...`; In case you use any kind of spring cloud discovery please look it up yourself in the according docs.

If the url looks good to you and just the name resolution fails you could test if it helps to use the ip for registration. In case you are using the SBA client try setting `spring.boot.admin.client.instance.prefer-ip=true`; In case you use any kind of spring cloud discovery please look it up yourself in the according docs.

If the name resolution doesn't fail, you may have a network routing error - can't help you with that.

And last but not least - may be everything correct and there is just not running a service on the specified url...

P.s. There is no need to ask twice - I just saw your message in the gitter channel - and would have answered there. Just consider people are working in a different timezone and are sleeping while you work.
