### ISSUE TITLE
How to send the authentication credentials for management endpoints from boot client to admin server?

### ISSUE THREAD

**Issue by aayushgupta** [codecentric/spring-boot-admin#136]
I have multiple boot applications, all registering to same boot admin server. These applications have secured management endpoints having different authentication credentials (different username/ password for each application).
The boot admin UI pops up the window to enter the credentials for each application. Is there a way to pass the authentication credentials from client, so that admin server automatically reads it and connects to secure endpoints.

**Comment by joshiste** [comment]
Currently this is not possible.

My 5 cents:
If you hand over the credentials to the admin server so that you can access the endpoints via the zuul proxy at `/api/applications/{id}/*` without credentials you don't have achieved any additional security.
You could then secure the admin server with the result, that one password gives you access to all your applications. So in turn you could also use the same credentials for all your applications.

Just an additional note:
The health-endpoint is currently required to report the status (details not needed) without credentials. For achieving this see [Spring Boot Reference - HTTP health endpoint access restrictions](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#production-ready-health-access-restrictions)

**Comment by ragnoros** [comment]
Hi, 
I am trying to achieve the same thing. 
Isn't it possible with the properties : 
`spring.boot.admin.username 
 spring.boot.admin.password`
I added `spring-boot-starter-security` to my `spring-boot-admin-server`.
And from my client user the two properties i found in the wiki to set the authentication needed to reach admin server endpoints (every endpoint is protected by basic auth) . 
i am getting `Failed to register application as ...(http://localhost:9110/api/applications): 403 Forbidden` . 
Can you help ? 

Thanks.

**Comment by joshiste** [comment]
`spring.boot.admin.username` `spring.boot.admin.password` are the credentials used for the post-request to register the application. If you get a 403 you got a wrong password/user.

If you only include a spring-security and have no password set in the admin server a random one is generated. See [Spring Boot Reference Guide - Security](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-security)

**Comment by ragnoros** [comment]
My bad.  
I did it wrong.  I misspelled the property name.  I should have double checked this.  
Sorry i bothered you and thank you for answering me.

**Comment by deki** [comment]
Hmm if a secured client application registers with a boot admin server basic authentication popups open up in a loop in the browser and the admin gets unusable. I think a better solution is needed. Why not adding configuration attributes for the credentials as proposed by @aayushgupta (in case https is used the password will not get disclosed)?

**Comment by RobWin** [comment]
I also like the idea.

**Comment by ethlo** [comment]
This is currently a showstopper for us. Would you consider a PR?

**Comment by joshiste** [comment]
@ethlo depends on the solution. I did try to include the credentials in the url via <user>:<pwd>@server generally works just the zuul needs some tweak.

**Comment by ntatsumi** [comment]
For basic HTTP authentication, the Zuul tweak you need is `zuul.sensitive-headers=Cookie,Set-Cookie` property. Zuul has the property set to 'Authorization,Cookie,Set-Cookie' by default. You need to prevent Zuul from stripping out the Authorization header.
