### ISSUE TITLE
Spring Boot Admin Certificate error in the logs for some different port.

### ISSUE THREAD

**Issue by mciumac** [codecentric/spring-boot-admin#1430]
I am using Spring Boot Admin 2.2.2 . I configure it to use SSL. I register SSL applications with it.
Everything works good as suppose to. Able to access Spring Boot Admin through https and its applications info from it. But when I look in the logs I see this (see below). I get this error because at some point it uses underneath the ip address. But all my urls for spring boot admin and registered applications are using dns names and certificate are also for dns name. It does not affect functionality of the app. So the question is why ip address is used at some point and what should I do to fix this.

I do have a certificate that is for dns name (it is not selfsigned) otherwise I wouldn't be able to successfully call the SBA url. The port 57868 from the error it is not even the port 
that the SBA is running on. This error I see in the logs while navigating through SBA. All the urls configured in application.properties files are using dns name.
I expect this error will go away if I add the certificate for ip address also. But why do I have to do it , if I use DNS name and again the call with error above is happening behind the scenes that I don't have control of on some different port.

2020-04-16 12:52:33.535 [a2-admin-server,,,] [reactor-http-nio-2] ERROR reactor.netty.tcp.TcpServer - [id: 0x058d8c1f, L:0.0.0.0/0.0.0.0:8760 ! R:/10.1.42.56:57868] onUncaughtException(SimpleConnection{channel=[id: 0x058d8c1f, L:0.0.0.0/0.0.0.0:8760 ! R:/10.1.42.56:57868]})
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLException: Received fatal alert: certificate_unknown

**Comment by mciumac** [comment]
Certificate that is added to java cacert is signed by our company local ca. Both the signer and signed certificate are added to java cacert that is used. Is there  anywhere else the signer has to be added (since it is not publicly known signer) so it can be recognized by Spring Boot Admin application? If this is the case of this error.

**Comment by joshiste** [comment]
> The port 57868 from the error it is not even the port
that the SBA is running on.

The error contains to addresses the local socket of the server (`L:0.0.0.0/0.0.0.0:8760`) which tells you that the admin server is listening for all ip addresses on port 8760 and the remote address (`R:/10.1.42.56:57868`). The remote address is typically an ephemeral port and just denotes the socket of the client which initiated the tcp connection. That ip adresses and not hostname are printed is due to nettys implementation.

> Is there anywhere else the signer has to be added (since it is not publicly known signer) so it can be recognized by Spring Boot Admin application?

If you add the certificate to the JRE's trustkeystore (like you said you did) you should be fine.

Seeing this error on the server-side doens't make sense to me (unless you are doing some kind of mutual TLS).
In addition I don't see how it relate to Spring Boot Admin as it more looks like a problem with your TLS setup or netty.

What you can try is to include the  `spring-boot-starter-web` to your admin server so that the server will use tomcat (instead of netty) as http server to rule out that netty is causing problems.

**Comment by mciumac** [comment]
ok, thank you.
