### ISSUE TITLE
Rewrite UI

### ISSUE THREAD

**Issue by joshiste** [codecentric/spring-boot-admin#145]
Currently we have following issues with the ui, wich pops up quite often:
 * Java-devs are quite unfamiliar with the node.js based build
 * No support for configuring/customizing the ui
 * No support for i18n
 * No sophisticated support for authentication

Additionally we could improve these things:
 * Responsive design
 * Use server sent events (SSE) for status updates to reduce lag for status updates

So after-all I think the ui should be rewritten. Currently i'm tinkering with doing that embracing a roca-style ui using thymeleaf.

**Comment by steve-oakey** [comment]
Just my opinion, but I think the UI as it is now is fine.

- unsure what type of customization you are referring to. What would you
want that wouldn't require modifying the source? Custom styling?

- i18n could be  achieved using something like angular-translate (
https://github.com/angular-translate/angular-translate)

- authentication can be done however the consumer wants to implement it.
For example, I am using the Admin server with SSL mutual authentication.
Are you referring more to authenticating with the registered apps? OAuth
could maybe help with this.

- perhaps this is true, but I don't see that as a reason so rewrite the UI.
Right tools for the right job. Personally, this project helped me learn
about a node based build and angular applications.

Ultimately you are making the call on this, but I wanted to share my
experience with it. I have been using and following the repo for about a
year now and have been quite happy with everything. I'm surprised that
Pivotal has not shown interest in adopting this project as part of Spring
Boot Actuator.

Keep up the good work.

**Comment by joshiste** [comment]
Hey steve, thanks for sharing your opinion. 
I am currently really not sure what todo here. So I submitted this issue and I am really glad that you joined the discussion.

For customizing there was for example a request for changing the html-title. And it's totally static an not configurable (e.g. disabling views)
And for example the activiti-"extension" is merged in to the "core"-ui may be it would be nice to use some kind of extension-mechanism.

**Comment by joshiste** [comment]
@steve-oakey I am interested in how you solved security. Do you have some info on this? May be you want to write a short section in the docs on this?

**Comment by steve-oakey** [comment]
We solved the security problem by using SSL mutual authentication on the
Admin Server application and passing the user credentials to the monitored
applications via headers in a ZuulFilter. The applications run behind a
firewall and are only accessible through a reverse proxy (nginx) and from
the Admin Server. This works well in a private organization where you can
generate your certificates using a private CA.

I am sure that this could be solved somehow with OAuth2 as well however I
don't have experience working with it. Our applications are behind a
corporate firewall so we don't use OAuth2 providers and don't have our own
resource/token server at this time.

I could certainly write something in the docs about "Securing Using SSL
Mutual Authentication" and document what I've done if you are interested in
implementation details.

-Steve

**Comment by ptahchiev** [comment]
Hello,

let me join in this discussion by sharing my thoughts. 

 - Indeed I have no experience with node.js builds but frankly I don't really mind what you use to build the project, as long as the result is jar file (something that all java developers know).
 - The configuring/customizing is a must IMHO. The spring framework is designed to be easily extensible and so should be the actuator UI. Otherwise what happens is people extend the spring-boot actuators, add some new actuators, and then they can't extend the UI. A few more thoughts on this one - why not take out all CSS files in another jar called `spring-boot-admin-theme-default` and so if user wants to have their own theme, they simply include their own webjar, instead of the default theme jar.
 - +1 for angular-translate. Looks like the way to go.
 - The way I see the authentication thing is the following - 1) there must be a login screen 2) there must be a stub that returns always a hard-coded token. 3) The user can specify a property to change the URL of the stub and return real (expiring) tokens. Whether it will be implemented with Oauth or not is details.

**Comment by steve-oakey** [comment]
For authentication, a login page that matches the look and feel of the rest
of the UI would be nice, but authentication to the web application itself
should be up to the user. I may want to implement Basic Auth, LDAP
authentication, SSL mutual authentication, OAuth, leave that up to me.

The bigger issue right now is handling the authentication to the
applications the Spring Boot Admin application is monitoring. Currently
only basic auth (or nothing is supported) and this requires every client
application to have the same username/password. This is not ideal. To me a
better solution is to proxy the user credentials to the applications being
monitored (not required to simply check the health but for each of the
other pages) and have each of those applications decide if the user is able
to access the specific endpoints.

- Steve

**Comment by mar1ged** [comment]
From my point of view the UI does not need to be changed. It looks good and is easy to handle.

If I were the one to decide I would say add more functions (like the timer metrics ;-)) instead of putting effort into changing the UI. At least as long as the "old" UI does not keep you from adding new functions or makes it unbearable difficult.

**Comment by silma85** [comment]
Hi, first of all I want to say thanks for this good application, I'm trying to convince my superiors to use it (and consequently, Spring Boot). The corporation is interested in metrics and customized info and I, as a Java developer with no previous experience in Node.js, am having difficulties in exposing a custom Actuator endpoint. A more user-friendly way to add endpoints to the "detail" page (for example) would be really nice; or, at least, some documentation on how to add a custom endpoint. Also a way to start-stop registered applications would be much appreciated.

**Comment by tobiasflohre** [comment]
I'd also say that the UI is fine as it is, but some kind of plugin system to add custom pages would be good. What if we make the "apps" dynamic? The thing you call "apps" are the pages that are reflected in the navbar. It would be cool if you could package your new endpoint in a separate webjar that would be picked up by that plugin mechanism.

Maybe naive, but what about this:
- Projects with new endpoints package their own webjar with their JavaScript and their view.
- We have a configuration with the following information per app / endpoint
  - url (/env)
  - templateUrl (views/apps/environment.html)
  - controller (environmentCtrl)
  - JavaScript - Location (js/app.js)
- We import all different JavaScript - Locations in index.html (maybe through rendering with Thymeleaf)
- The AngularUI reads that configuration and generates everything regarding apps dynamic

Maybe naive, because I don't have any clue about Angular. What do you think?

**Comment by joshiste** [comment]
I was also pondering if there is some way to make the ui "pluggable".
I think it's very clear how to cut the modules. 
I question if this is solvable with a single Angular SPA or if the ui should be split into multiple pages....

Currently I am really missing the time to do some prototyping here.

**Comment by joshiste** [comment]
I've done some [work on this on a branch in my repo](https://github.com/joshiste/spring-boot-admin/tree/pluggable-ui).
First I try to separate the ui into independent angular-modules.
Next step is dynamic loading of these modules.
I don't want to pull thymeleaf in. I'd rather try to serve the moduls via a spring 4.1 resource chain...

**Comment by rovangju** [comment]
I also support keeping the UI track as is; the angular approach is a solid, forward looking one that will make this specific module/component more attractive for those with UI specific skill sets to contribute.

**Comment by joshiste** [comment]
The biggest pain was that developers weren't able to add their own modules in the UI. I've committed the changes to make the UI modular to the master branch. The snapshots should be available in a few minutes. 
Additional to the modularization the UI and has been modernized to a recent version of angular and now uses webpack for packaging.
For some more informations see the [commit message](https://github.com/codecentric/spring-boot-admin/commit/eae1ff46121a2abfc3ac5703edcf37967b092e8c) 

I'm keen on closing this issue. Yes, not all of the problems listed above are solved, but the decision is to evolve the UI and not to rewrite it from scratch.
