### ISSUE TITLE
Separate spring-boot-admin-cloud module for netflix libraries

### ISSUE THREAD

**Issue by RobWin** [codecentric/spring-boot-admin#148]
Hello,

if you don't use Spring Cloud and its Netflix libraries, it would be nice if spring-boot-admin does not include any Spring Cloud libraries.
Is it possible to create a spring-boot-admin-cloud module which must be added to your dependencies to support the Spring Cloud Discovery?

**Comment by joshiste** [comment]
Zuul is used regardless of using eureka discovery, so this will be always included.
And maybe it's possible to make the discovery part optional, which I would prefer instead of adding another module.
Is there any special reason for you to not include the discovery part or is it just to get rid of unnecessary dependencies?

**Comment by RobWin** [comment]
Yes. Just getting rid of unnecessary dependencies.

**Comment by joshiste** [comment]
I did take a look at the dependencies for the simple sample. In my opinion we really rely on the dependencies pulled in. And Discovery/Eureka isn't - so here is nothing to optimize.
