### ISSUE TITLE
Unable to start Admin due to Zuul ProxyRouteLocator issue

### ISSUE THREAD

**Issue by sallampalli** [codecentric/spring-boot-admin#153]
I think I have a similar situation mentioned in 
https://github.com/codecentric/spring-boot-admin/issues/120
I am trying to centralize Eureka, Zuul, Config Server, SpringBoot Admin Server etc.. in a single component.
(Using spring cloud parent Angel.SR6 and SpringBootAdmin 1.3.2)

@SpringBootApplication
@EnableAdminServer
@EnableEurekaServer
@EnableZuulProxy

This combination results in

Could not autowire field: private org.springframework.cloud.netflix.zuul.filters.ProxyRouteLocator org.springframework.cloud.netflix.zuul.ZuulProxyConfiguration$RoutesEndpointConfiguration.routeLocator; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.springframework.cloud.netflix.zuul.filters.ProxyRouteLocator.

If I remove AdminServer out of the picture, it works just fine. Also, how do I tell the AdminServer to use the same port defined for eureka but a different context path ?

**Comment by jvmlet** [comment]
> Also, how do I tell the AdminServer to use the same port defined for eureka but a different context path 

spring.boot.admin.context-path ?

**Comment by joshiste** [comment]
>I am trying to centralize Eureka, Zuul, Config Server, SpringBoot Admin Server etc.. in a single component.

I don't think this is a good idea. It's totally opposed to the microservice idea....
EurekaServer is for ServiceRegistry/Discovery
AdminServer is for Monitoring
ZuulProxy is a proxy-server / api-gateway / edge-service
Three totally unrelated concerns which you should handle speparate.

... and since the admin server itself contains a zuul proxy I don't this this would mix very well.
So adding the EurekaServer should work but not adding the zuul.

**Comment by mrumpf** [comment]
I would like to disagree here. ZuulProxy is a functionality that can be used in different ways.
One is the "API Gateway / Edge Service" way how Netflix is using Zuul. The other one is to do some simple proxying to admin functionality for example that is used by a small group of admins only.

We have an admin microservice which does several things:
1. Host the codecentric spring-boot-admin 
2. Host the Hsystrix Dashboard
3. Host the Netflix Vector UI
4. Use the admin server as a Zuul proxy to different admin features of other microservices

I agree with you that the non-related features "Eureka", "Spring Cloud Config", and "Spring Boot Admin" should not be put into one microservice, but adding several admin related features in one service is a valid approach in my opinion. We are not running on a PaaS platform yet and creating a new microservice involves some initial setup effort and continuous maintenance effort from operations. Adding a new microservice in such a corner case is not a reasonable option.

**Comment by joshiste** [comment]
>I would like to disagree here. ZuulProxy is a functionality that can be used in different ways. One is the "API Gateway / Edge Service" way how Netflix is using Zuul. 

You are right. But a ZuulProxy which is needed to drive your business must not be included in your monitoring or dashboard applications.

> ... but adding several admin related features in one service is a valid approach in my opinion.

For your business applications you are doing microservices and for your admin tools you are building a monolith? Come on!
If you entangle all these things you can't release/update/deploy them separate. If you just put it all together in one service for the sake of a single adress, put a reverse proxy / edge service in front.
But as always it is a trade-off depending on your context.

> We are not running on a PaaS platform yet and creating a new microservice involves some initial setup effort and continuous maintenance effort from operations.

Three words: cattle not pets
Doing microservices puts you in the need for automation.

**Comment by mrumpf** [comment]
:) I also prefer living in a simple world. Unfortunately reality is more complex. The corporate environment I live in changes very slowly. Yes, we are automating a lot of stuff, providing new VMs for an application is not part of it because our IT provider still lives in the "old" world and I cannot change that. Besides that the customer has chosen to use static infrastructure instead of a dynamic cloud environment. These are the reasons why we are forced not to move every little aspect into a separate microservice because the maintenance bill would explode.
But anyway, thanks for your time.
