### ISSUE TITLE
Support Apache Dubbo

### ISSUE THREAD

**Issue by ChinaJeckXu** [codecentric/spring-boot-admin#1540]
Are there any plans to support Apache Dubbo?
Including some basic monitoring information, such as: connection status。

**Comment by joshiste** [comment]
Since apache dubbo is a RPC framework I wonder what do you expect for support?

For Metrics you should ask at https://github.com/micrometer-metrics/micrometer (or implement your own)
For HealthIndicators (other actuator endpoints) you should ask at https://github.com/spring-projects/spring-boot (or implement your own)

If there are any specialized metrics for dubbo we could add specific views to SBA (or you add it as custom view)
