### ISSUE TITLE
ApplicationRegistrator uses wrong rest temaplate

### ISSUE THREAD

**Issue by jvmlet** [codecentric/spring-boot-admin#166]
Hi
My spring boot application uses `MappingJackson2HttpMessageConverter` with objectMapper that is configured to include type class field :
````
objectMapper.enableDefaultTyping(ObjectMapper.DefaultTyping.NON_FINAL, JsonTypeInfo.As.PROPERTY);
````

On the other hand, `ApplicationRegistrator` uses `RestTemaplate` that **disregards** configured converter and adds the default one.
 As the result, the message can't be converter from body stream to object, as the mapper tries to find '@class' property on received JSON.

````java
protected RestTemplate createRestTemplate(AdminProperties admin) {
		RestTemplate template = new RestTemplate();
		template.getMessageConverters().add(new MappingJackson2HttpMessageConverter());
		....
		return template;
	}
````

**Comment by joshiste** [comment]
So did I get it right, that the response from the spring boot admin server contains the class-field and the `ApplicationRegistrator` can't read it?

It was on purpose to not use a shared `MappingJackson2HttpMessageConverter` in the spring-boot-admin-starter-client. The business applications might need their own customized one and that would break communication to the admin server .

Is it really necessary to make a custom `objectMapper` in the admin server, so that the answer has the class-field?
If that's the case you should instantiate the `ApplicationRegistrator` in the client yourself with an according configured `RestTemplate`. The `SpringBootAdminClientAutoConfiguration` will then use your bean.

**Comment by joshiste** [comment]
p.s. that is one of the problems which occur when you add the admin to your business apps. Don't you have? :grinning:

**Comment by jvmlet** [comment]
> So did I get it right, that the response from the spring boot admin server contains the class-field and the ApplicationRegistrator can't read it?

It's actually the opposite, the rest template sends `Application` without `@class` attribute, but argument resolver uses mapper with enabled default typing and fails.
I've managed to force rest template to use object mapper with `enableDefaultTyping`, but then javascript code fails to parse json with `@class` attributes.
I'll try to deploy boot admin within it's own context (dispatcherServlet).

**Comment by joshiste** [comment]
Hmm can you put up a small sample? I just don't comprehend the whole
problem.
