### ISSUE TITLE
Allow to configure connection timeout

### ISSUE THREAD

**Issue by dmwb** [codecentric/spring-boot-admin#168]
For heavy loaded apps. Spring boot admin very frequently have this exception, after refreshing details page...

![image](https://cloud.githubusercontent.com/assets/17462277/13682060/10276436-e6b5-11e5-827d-8509e17a42b0.png)

**Comment by joshiste** [comment]
I guess you have a very slow health check, so that the request through the zuul-proxy gets a timeout.


It should be already possible to set the timeout via `zuul.host.socket-timeout-millis` (default: 10000).

But you should keep your health-indicators doing fast checks... Maybe you should probe your `/health` endpoint during load-tests.

**Comment by dmwb** [comment]
You're right. Health check is very slow, even if call health url directly. Thanks, for the suggestion I'll try it.
