### ISSUE TITLE
Heap Dump hitting Server problem during the middle of the download

### ISSUE THREAD

**Issue by AndrewGotz** [codecentric/spring-boot-admin#1764]
Using SBA version - 2.3.1
Chrome Version - Version 91.0.4472.124 
Spring Boot Version - 2.3.12.RELEASE

Right now sometimes when I download a heap dump from SBA it will fail due to a server problem. I have tried other browsers and many people on my team have had the same issue with various degree's of success but everyone has hit this problem often enough it has become an issue.

Interesting is it seems to be the longer its forced to download the more likely the problem as sometimes if it finishes quick enough it works just fine. Myself and others are on different internet connections as we are working from home, we do have the same VPN we connect to so it potentially could be some issue with that but wondering if anyone has any suggestions?

This happens often enough its almost impossible to grab a heap dump when we need to for an ongoing issue.

![HeapDumpServerProblem](https://user-images.githubusercontent.com/30178816/124624417-778eff00-de42-11eb-864b-dd471bb1dc57.PNG)

**Comment by AndrewGotz** [comment]
@erikpetzold  Just wondering if any of you guys working on SBA had any idea of this. Tried to see if it was a network issue but did a couple different tests and keep seeing the same results. Randomly it will kill the connection off and stop downloading.

**Comment by erikpetzold** [comment]
Hi @AndrewGotz ,

sorry but at the moment I have no real idea how to help. I don't think this is an SBA iissue.

Sounds like some kind of timeout ("happens when the download takes longer").

Do you see any error in server logs? 
Is there some kind of proxy in front of SBA? Can you see the logs of that proxy?
Are there some vpn logs?
Can you use a stopwatch to check if it fails always after the same time?
