### ISSUE TITLE
Spring Boot Admin UP but status is DOWN

### ISSUE THREAD

**Issue by hendisantika** [codecentric/spring-boot-admin#1784]
Hi All, 
I already run the services including. But Spring Boot Admin UP but status is DOWN.

https://github.com/hendisantika/SpringBootAdminDemo

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/3713580/127756903-faaf8281-42bf-4b51-a4f6-55f3fb9d48ff.png">

Any advice?

Thanks

**Comment by Glosur** [comment]
Is spring boot admin exposing it's actuator endpoints ?

**Comment by hendisantika** [comment]
Hi @Glosur ,

Yes, it is.

**Comment by Glosur** [comment]
I can see you are logged in the top right of your screen, did you add configuration telling spring boot admin how to log to probe itself ?

**Comment by hendisantika** [comment]
Hmm ... No, I'm not.

How to do that @Glosur ?

**Comment by Glosur** [comment]
Mmmh

Could you share your Spring boot Admin configuration file ?

**Comment by hendisantika** [comment]
I have share the repo link above @Glosur .

**Comment by SteKoe** [comment]
Hi, since you are using Eureka, you have to add some properties to your SBA configuration as documented in [5.2.3](https://codecentric.github.io/spring-boot-admin/2.4.3/#_eureka):

```
eureka.instance.metadata-map.user.name=${spring.security.user.name}
eureka.instance.metadata-map.user.password=${spring.security.user.password}
```

Since this issue is not a bug or enhancement but a question, I'd beg you to ask questions in our [Gitter](https://gitter.im/codecentric/spring-boot-admin) next time :)

**Comment by hendisantika** [comment]
OK sure. Thank You @SteKoe
