### ISSUE TITLE
UI Plugin system

### ISSUE THREAD

**Issue by RobWin** [codecentric/spring-boot-admin#180]
Hello,

I know this is an Epic and the UI has to be rewritten :)
But I think it would be a great feature if spring-boot-admin would have a Plugin system like ElasticSearch Kibana which allows to extend the UI via custom plugins.
We have developed some custom Spring Acutator endpoints and we would like to display the ouput via spring boot admin.

I could assist in developing such a plugin system.

Kind regards,
Robert

**Comment by joshiste** [comment]
Hi,
I've already made a lot of progress on this, as you can see in [joshiste/pluggable-ui](https://github.com/joshiste/spring-boot-admin/tree/pluggable-ui).
The acitivi-view has been moved into a separate module (a simple jar with a bit of angular-javascript and static assets, which can be pulled-in via maven) and is a good example on how to implement a simple ui module.

I'll merge this after the 1.3.3 release of spring boot admin (which itself waits for the Brixton Release) into the master so that a snapshot-build will get available. 

duplicates #145

**Comment by RobWin** [comment]
Very nice :)

**Comment by nickgr6** [comment]
@joshiste it seems like you can only add a custom plugin / view when adding it as submodule to the base project, as described in my stackoverflow answer: https://stackoverflow.com/a/44822119/639033
Is that true, or am I missing something?

**Comment by joshiste** [comment]
@nickgr6 yep thats right here is a sample project doing that https://github.com/joshiste/spring-boot-admin-java-magazin
