### ISSUE TITLE
Problem with boolean JMX attribute

### ISSUE THREAD

**Issue by lightoze** [codecentric/spring-boot-admin#184]
Initial DOM for boolean attribute is:
```html
<select ng-switch-when="boolean" class="span5 ng-scope ng-pristine ng-valid" ng-model="attr.value" ng-disabled="!attr.rw" ng-options="val for val in [true, false]"><option value="?" selected="selected" label=""></option><option value="0" label="true">true</option><option value="1" label="false">false</option></select>
```

After attributes are read, attribute field remains empty, however DOM changes to:
```html
<select ng-switch-when="boolean" class="span5 ng-scope ng-pristine ng-valid" ng-model="attr.value" ng-disabled="!attr.rw" ng-options="val for val in [true, false]"><option value="? boolean:false ?"></option><option value="0" selected="selected" label="true">true</option><option value="1" label="false">false</option></select>
```

Also, as a side note - non-primitive number/boolean types are not handled as good as their primitive counterparts.

**Comment by joshiste** [comment]
I fixed the issue with the boolean. I noticed this error while doing the ui modularization. But I've not backported the support for the wrapper types since would be a lot more work.
My plan is to merge the modular ui after the next spring boot admin release (which itself is waiting for Brixton which is currently scheduled for 30th of April)
