### ISSUE TITLE
Undefined error in ui ,jvm thread dump

### ISSUE THREAD

**Issue by jzcccc** [codecentric/spring-boot-admin#1863]
admin version 2.5.4
spring boot version 2.4.1
 
Undefined error in jvm thread dump
![image](https://user-images.githubusercontent.com/26700791/143419455-ee440de7-35f3-4d77-abb5-9f42cf88a5e3.png)
this is my /actuator/threaddump json file
[Uploading actuator-threaddump.txt…]()

**Comment by SteKoe** [comment]
Hi @jzcccc,

could you please provide the thread dump file? I can't access it. 

TIA,
SteKoe

**Comment by jzcccc** [comment]
[threaddump.txt](https://github.com/codecentric/spring-boot-admin/files/7630600/threaddump.txt)
threaddump api response json

**Comment by SteKoe** [comment]
Thanks for posting your thread dump! It seems that you have configured Jackson in the service you are monitoringto use `snake_case` fields in JSON instead of `camelCase`. Since SBA relies on `camelCase`, please check your Jackson configuration and make sure that the actuator endpoints are sending the fields as `camelCase`. 

Duplicates #751.

**Comment by jzcccc** [comment]
Thanks. I'll check it again!!!
