### ISSUE TITLE
Failed to register application as null - Registration client application failed

### ISSUE THREAD

**Issue by Explox** [codecentric/spring-boot-admin#190]
Today,

I tried to implement your Spring Boot Admin application to monitor mine. But after a lot of time trying and fixing the issue I had while following your documentation. I ended up with this log in my console of my client that, it seems, can't connect to the server :

2016-05-07 18:50:53.085  WARN 4568 --- [pool-3-thread-1] d.c.b.a.services.ApplicationRegistrator  : Failed to register application as null at spring-boot-admin (http://localhost:8090/demo//api/applications): serviceUrl must be set when deployed to servlet-container

My client and server are working on the same server but with a different port. They work but they can't interact between them.

Do you know what could cause this problem ?

PS : I followed your documentation

**Comment by joshiste** [comment]
The guide misses a part about deploying to a servlet container - it just describes the embedded server mode. Please do what the error message tells you and set the `spring.boot.admin.client.service-url` for your client application using the url where your service is deployed (e.g. `http://localhost:8080/foo`)

**Comment by Explox** [comment]
Thanks a lot dude. Perfect response. I didn't know that I had to indicate this property. Works fine.

**Comment by sallampalli** [comment]
@joshiste  : What if the host is dynamic ? Is there a way we can give the port and context-path ? I know there is for embedded tomcat and I use it for my development purpose, but we deploy to a servlet container with different port and hosts can vary. In that case, I wouldn't prefer to give the host name , rather is there a way to specify spring.boot.admin.client.service-url-port and spring.boot.admin.client.service-url-context-path ?

**Comment by joshiste** [comment]
@sallampalli no there isn't. And if you have a question please ask in our [Gitter channel](HostInfoEnvironmentPostProcessor) instead of posting on old issues...

You could add a custom `EnvironmentPostProcessor` which computes the `spring.boot.admin.client.service-url` from other properties / hostname.
Have a look at spring cloud's [HostInfoEnvironmentPostProcessor](https://github.com/spring-cloud/spring-cloud-commons/blob/master/spring-cloud-commons/src/main/java/org/springframework/cloud/client/HostInfoEnvironmentPostProcessor.java).
