### ISSUE TITLE
Does the CVE-2022-22965 Vulnerability Affect spring boot admin？

### ISSUE THREAD

**Issue by qqhai007** [codecentric/spring-boot-admin#2013]
A Spring MVC or Spring WebFlux application running on JDK 9+ may be vulnerable to remote code execution (RCE) via data binding. The specific exploit requires the application to run on Tomcat as a WAR deployment. If the application is deployed as a Spring Boot executable jar, i.e. the default, it is not vulnerable to the exploit. However, the nature of the vulnerability is more general, and there may be other ways to exploit it.

**Comment by SteKoe** [comment]
Hi @qqhai007,

according to the OWASP maven dependency check, Spring Boot Admin is affected. To mitigate this critical issue, we have just released https://github.com/codecentric/spring-boot-admin/releases/tag/2.5.6 and https://github.com/codecentric/spring-boot-admin/releases/tag/2.6.5. Due to a bug in the sync process in Maven Central (https://status.maven.org/) the releases are not yet available.

**Comment by SteKoe** [comment]
Releases are now available via Maven Central :)
