### ISSUE TITLE
Failed to register application as Application

### ISSUE THREAD

**Issue by rahulgautam034** [codecentric/spring-boot-admin#2039]
My spring boot admin server working fine with url :- https://localhost:9091/ . The problem when I run the spring boot admin client then it getting error- **Failed to register application as Application*

below is admin configuration:
<img width="849" alt="Screenshot 2022-05-25 at 7 19 11 PM" src="https://user-images.githubusercontent.com/44476592/170278220-4b40b4d9-7f3d-4c71-a656-e7bc2ef20c5c.png">
*
This is the spring-boot client configuration:
<img width="701" alt="Screenshot 2022-05-25 at 7 20 43 PM" src="https://user-images.githubusercontent.com/44476592/170278406-eff8c158-132e-4504-887e-7227f095aa90.png">

**Comment by ulischulte** [comment]
Hi @rahulgautam034,

I think the problem lies in SBA Server's handling of the client certificate.
SBA Server can use client certificates to authenticate while registering and accessing the actuator endpoints. Have a look at the documentation https://codecentric.github.io/spring-boot-admin/current/#_using_mutual_tls .

If this doesn't solve your issue, we'll need further information.
At best you provide a complete sample project to reproduce the issue.

Regards,
Uli

**Comment by rahulgautam034** [comment]
HI @ulischulte ,

Thanks for replying. Both admin and client side I use the same certificates PKCS  type and this is the self signed certificate just to test the scenario.This repository is private so not possible to share anywhere.
Thanks,
Rahul

**Comment by SteKoe** [comment]
Since you cannot provide an example repository, we are not able to help here, sorry.
