### ISSUE TITLE
Helm Chart or pre build Docker Image

### ISSUE THREAD

**Issue by rowi1de** [codecentric/spring-boot-admin#2115]
- Currently it’s required to setup a spring boot admin server from scratch and figure out deployment options.
- It would be very helpful to have pre-build docker images and/or helm charts that could be configured
- was this already considered? There are some “unofficial” helm charts already https://github.com/evryfs/helm-charts/tree/master/charts/spring-boot-admin

**Comment by SteKoe** [comment]
Ho @rowi1de,

thanks for your question. Even though there exists a [Docker Repository for SBA](https://hub.docker.com/repository/docker/codecentric/spring-boot-admin) we do not officially maintain it. The Docker images are used for demos and other internal purposes. That's also the reason why the contained Spring Boot Admin application is very basic. In addition, the possibilities on how to configure SBA are too complex to offer Docker images for each and every way (i.e. security, service discovery using Consul, Eureka, Kubernetes, Self-Registration...).

Since Helm Charts are just one way to deploy applications, we also do not have officially released helm charts. We fully rely on the power of Open Source Developers out there offering solutions for this :)

Regards!
