### ISSUE TITLE
Spring boot admin server with gRpc endpoints

### ISSUE THREAD

**Issue by VenkateshSrini** [codecentric/spring-boot-admin#2131]
At present spring boot admin server access, the application endpoints that are exposed over HTTP and JSON. Additionally, it must have the capability to read these application health, readiness, liveness, and other metrics over gRpc also. When working on Kubernetes with fully gRpc protocol, just for the sake of these stats we will have to expose the HTTP endpoint which does not make it nice.

**Comment by ulischulte** [comment]
Hi @VenkateshSrini,

since there's no existing spring-boot-actuator-grpc-starter within spring-boot itself so far, there won't be any support of gRpc endpoints in Spring Boot Admin. 

Regards,
Uli

**Comment by VenkateshSrini** [comment]
@ulischulte I think it is all about the spring boot admin server team defining the Proto's first. Once we do this, then these proto definitions can be implemented in the app endpoints. So the development begins with designing the proto and extend it to Spring boot actuators and SteelToe libraries

**Comment by SteKoe** [comment]
Hi @VenkateshSrini, thanks four your reply!

Anyways, sorry to say, but no, it is not “all about the spring boot admin server team” to define this. We are not in any way (despite the naming) related to Spring Boot. We rely on the concept of Spring Boot Actuators and act as a thin-layer reverse proxy, offering a nice and readable UI. Since the Actuators expose REST only, we support REST only. 

It seems that you really would like to see a gRPC feature in Spring Boot, hence it is all about you to define the Proto’s first and extend them to Spring Boot Actuators. Whenever Spring Boot Actuators expose some gRPC functionality, we will start to check how to integrate them into Spring Boot Admin.

Best,
SteKoe
