### ISSUE TITLE
Applications not showing - this.endpoints.findIndex is not a function

### ISSUE THREAD

**Issue by Cimballi** [codecentric/spring-boot-admin#2138]
## Spring Boot Admin Server information

- **Version**:
2.7.5

- **Spring Boot version**:
2.7.4

- **Configured Security**:
basic auth

## Client information

- **Spring Boot versions**:
2.7.4

- **Used discovery mechanism**:
self registration

## Description

When I click on the Applications link, the page is almost empty, and there is an error in the browser console :
```
vue.runtime.esm.js:3019 TypeError: this.endpoints.findIndex is not a function
    at t.value (instance.js:48:27)
    at applications-list-item.vue:246:1
    at Array.some (<anonymous>)
    at o.hasShutdownEndpoint (applications-list-item.vue:246:36)
    at o.A (applications-list-item.vue:1:3288)
    at t._render (vue.runtime.esm.js:2654:28)
    at o.r (vue.runtime.esm.js:3844:27)
    at t.get (vue.runtime.esm.js:3415:33)
    at new t (vue.runtime.esm.js:3405:51)
    at Er (vue.runtime.esm.js:3861:5)
```

In the journal, ENDPOINTS_DETECTED :
```
{
    "endpoints": {
        "endpoints": {
            "caches": {
...
```

**Comment by ulischulte** [comment]
Hi @Cimballi,

which browser do you use? We assume that you are using Internet Explorer 11 (or earlier). findIndex() is an ES6 feature that is not supported by IE11 or earlier. Modern browsers (Chrome, Edge, Firefox, Safari, Opera etc.) support the feature.
However, we are also checking on our site how to fix the bug on IE11 if necessary.

Regards,
Uli

**Comment by ulischulte** [comment]
Hi @Cimballi,

as you may have seen, there is already a merged PR that addresses the problem. Can you check if the current SNAPSHOT solves your problem?

Regards,
Uli

**Comment by Cimballi** [comment]
There is that link I found on Internet, I am not using the same configuration approach, but maybe it's still related to the problem I am facing. "https://tnfhrnsss.github.io/docs/msa/spring/spring_boot_admin_customizing/"

**Comment by Cimballi** [comment]
@ulischulte So, the problem is related to json serialization. Should SpringBootAdmin work with Gson ? If not, is it possible to have the SpringBootAdmin json serializer working without having Jackson in the list of Spring http message converters ?

**Comment by ulischulte** [comment]
Hi @Cimballi,
the problem seems to be within your SBA clients configuration (which use GSON Serialization, as I suppose). SBA (and Spring Boot Actuator) itself uses Jackson. I think reconfiguring your MessageConverters within your registered clients might help. Have a look at this issue at Spring Boot: https://github.com/spring-projects/spring-boot/issues/12951#issuecomment-585385793
Reading that comment - it might be that your clients ObjectMappers are not working with Spring Boot Actuator as you may have set the client to explicitly asks for `"application/json"`.

If so, you might try to uncomment the supportedMediaTypes in the MessageConverter and try again. Something like:
`
		GsonHttpMessageConverter gsonHttpMessageConverter = new GsonHttpMessageConverter();
		gsonHttpMessageConverter.setGson(gson());
		//gsonHttpMessageConverter.setSupportedMediaTypes(Arrays.asList(MediaType.APPLICATION_JSON));
`

I hope that helps a little bit to clarify thing.
BTW - you can always find the current snapshot by cloning and building the master branch (git@github.com:codecentric/spring-boot-admin.git).

Regards,
Uli

**Comment by erikpetzold** [comment]
Snapshot builds are not deployed to maven central, but to an own snapshot repository hosted on github. You can add a maven repository with that url: 

```
   <repository>
        <id>sba-snapshot</id>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
        <url>https://maven.pkg.github.com/codecentric/spring-boot-admin</url>
    </repository>
```

**Comment by Cimballi** [comment]
@ulischulte I ended customizing the Gson converter so that if it cannot convert a message (the SBA ones), then it will fall back to using Jackson. It's a bit hacky but it works. Thanks for your help !
