### ISSUE TITLE
In Spring Security 5.7.0-M2, WebSecurityConfigurerAdapter is deprecated

### ISSUE THREAD

**Issue by huyu6** [codecentric/spring-boot-admin#2166]
A Spring Security configuration for your server could ;
before like this 
public class SecuritySecureConfig extends WebSecurityConfigurerAdapter {

  private final AdminServerProperties adminServer;

  private final SecurityProperties security;
...

how to config now?

**Comment by SteKoe** [comment]
Hi @huyu6,

thanks for opening an issue on GitHub. You have to migrate to the new concepts of Spring Security. There are a bunch of different guides out there in the web (e.g. https://www.baeldung.com/spring-deprecated-websecurityconfigureradapter). We have migrated  as well in SBA 3 (see https://github.com/codecentric/spring-boot-admin/blob/experimental/spring-boot-3-playground/spring-boot-admin-samples/spring-boot-admin-sample-servlet/src/main/java/de/codecentric/boot/admin/SecurityPermitAllConfig.java#L41) 

Since your problem is not directly related to SBA itself. I will close this issue here.

Regards,
SteKoe
