### ISSUE TITLE
login exception

### ISSUE THREAD

**Issue by JavaLionLi** [codecentric/spring-boot-admin#2218]
## Spring Boot Admin Server information

- **Version**:
  
3.0.0-M8

- **Spring Boot version**:
  
3.0.1

- **Configured Security**:
  
```java
@EnableWebSecurity
@Configuration
public class SecurityConfig {

    private final String adminContextPath;

    public SecurityConfig(AdminServerProperties adminServerProperties) {
        this.adminContextPath = adminServerProperties.getContextPath();
    }

    @Bean
    public SecurityFilterChain filterChain(HttpSecurity httpSecurity) throws Exception {
        SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
        successHandler.setTargetUrlParameter("redirectTo");
        successHandler.setDefaultTargetUrl(adminContextPath + "/");

        return httpSecurity
                .headers().frameOptions().disable()
                .and().authorizeHttpRequests()
                .requestMatchers(adminContextPath + "/assets/**"
                    , adminContextPath + "/login"
                    , "/actuator"
                    , "/actuator/**"
                ).permitAll()
                .anyRequest().authenticated()
                .and()
                .formLogin().loginPage(adminContextPath + "/login")
                .successHandler(successHandler).and()
                .logout().logoutUrl(adminContextPath + "/logout")
                .and()
                .httpBasic().and()
                .csrf()
                .disable()
                .build();
    }

}
```

- **Webflux or Servlet application**:
  
servlet

## Client information

- **Spring Boot versions**:
  

- **Used discovery mechanism**:
  

- **Webflux or Servlet application**:
  

## Description
Enter the login page and enter the account password
![HRDM2O)GOE6J5G8S48NH0X5](https://user-images.githubusercontent.com/31852897/211822151-0717dda2-e710-4bee-bd8d-7226e7f2499e.png)
After logging in successfully, I jumped to the garbled page.
![ZDSE$0V0{_P}Q77W3_8RG(K](https://user-images.githubusercontent.com/31852897/211822291-b84bc8c2-0ef8-452d-bed1-9ceeb21cdeb8.png)

**Comment by erikpetzold** [comment]
Hi @JavaLionLi 

you don't see a "garbled page", that is how the css looks like 😂 
If you have a look at the url you see this a css file being displayed. Normally it would be loaded by the javascript framework in the background.

I think here the problem is, that the frontend is requesting the variables.css very early, but in your security config this file needs authenticated access. So instead of returning the css file, the login page is shown. After login the file can be loaded and is then displayed as there is some kind of redirect to the originally requested resource after login.

The fix would be to allow access to this file without authentication (it does not contain any sensible information, just styling). See the servlet example here: 
https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet/src/main/java/de/codecentric/boot/admin/SecuritySecureConfig.java#L68
`.requestMatchers(new AntPathRequestMatcher(this.adminServer.path("/variables.css"))).permitAll()`

Hope that helps

@SteKoe I remember we discussed something like this, was this required because of the new theming? I think we did not want to require everyone to add this line and you wanted to change something? Otherwise we would need to update the docs.
I can reproduce it with the servlet sample when commenting out the line. The login page itself uses the variables.css for styling the login page.

**Comment by JavaLionLi** [comment]
> Hi @JavaLionLi
> 
> you don't see a "garbled page", that is how the css looks like 😂 If you have a look at the url you see this a css file being displayed. Normally it would be loaded by the javascript framework in the background.
> 
> I think here the problem is, that the frontend is requesting the variables.css very early, but in your security config this file needs authenticated access. So instead of returning the css file, the login page is shown. After login the file can be loaded and is then displayed as there is some kind of redirect to the originally requested resource after login.
> 
> The fix would be to allow access to this file without authentication (it does not contain any sensible information, just styling). See the servlet example here: https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet/src/main/java/de/codecentric/boot/admin/SecuritySecureConfig.java#L68 `.requestMatchers(new AntPathRequestMatcher(this.adminServer.path("/variables.css"))).permitAll()`
> 
> Hope that helps
> 
> @SteKoe I remember we discussed something like this, was this required because of the new theming? I think we did not want to require everyone to add this line and you wanted to change something? Otherwise we would need to update the docs. I can reproduce it with the servlet sample when commenting out the line. The login page itself uses the variables.css for styling the login page.

Thanks for your reply. I think this matter should not be handled by users. I hope we can optimize it
