### ISSUE TITLE
Spring Boot Admin Server: Metrics View Is Empty

### ISSUE THREAD

**Issue by nickman** [codecentric/spring-boot-admin#227]
Spring Boot Admin 1.3.4
Linux 64, Oracle JVM 1.8.0._65

At some point during my development, the Metrics tab in the Admin UI stopped showing metrics for connected client applications.

![image](https://cloud.githubusercontent.com/assets/597608/16636141/2f2a1f12-43a4-11e6-9b6a-6e33a6260112.png)

I am pretty sure I saw them there at some point, but I have tried back tracking and cannot get metrics to show up any more. If I retrieve the **/metrics** http endpoint directly, I can see the metrics (e.g. http://clientapp:7081/metrics) but nothing shows up in the admin UI.

Everything else seems to be working perfectly and I am not seeing any errors in the client or the admin server.

What should I be looking at to debug this ? I would really like to get those metrics back.

Thanks.

**Comment by tjuchniewicz** [comment]
I have the same issue. How to debug this?

**Comment by joshiste** [comment]
Please have a look at your browser dev-tools. Look at the console and networking tab.

**Comment by nickman** [comment]
Here's what I see in the tools console:

```
Uncaught SyntaxError: Unexpected token =
recorder.js:410 Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
player.js:939 Uncaught SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
angular.min.js:97 Could not read server sent event! Event {}(anonymous function) @ angular.min.js:97journalEventSource.onerror @ app.js:211
```

That's minus network call, which all look fine except that all the HEAD requests fail. (Do I need to implement that ?)

**Comment by joshiste** [comment]
ok so the first two errors aren't from spring boot admin. I guess it's from selenium ide (or similar) the third is the long polling timeout, which is also no problem.

Since the garbage collections stats are shown in your screenshot, the metrics endpoint in general seems to work.
The metrics tab only shows metrics with the `gauge.` or `counter.` prefix. Can you check your applications `/metrics` for these values? If the endpoint doesen't provide such the ui can't display 'em.

**Comment by joshiste** [comment]
The HEAD calls are made to detect if certain endpoints are available. So no you don't need to implement that.

**Comment by tjuchniewicz** [comment]
> The metrics tab only shows metrics with the gauge. or counter. prefix.

Thanks for explanation. This is my case. Are there any plans to make it more general view? I have my own metrics. Is there possibility to show them?

**Comment by joshiste** [comment]
The questions is how to visualize the different metrics. Until now it was simple to render gauges and counters as bars. Other metrics (jvm, datasource, ...) are shown in the boxes above.
What are those metrics you want to show? Don't you use the CounterService so that your metrics are prefixed with `counter.`

**Comment by nickman** [comment]
Now I understand. When I prefixed all my counter metrics with "**counter.**" they all rendered correctly.

**Comment by tjuchniewicz** [comment]
@joshiste thanks for explanation. Seems reasonable. Maybe other, not known metrics could be just listed in table?

**Comment by joshiste** [comment]
@tjuchniewicz If I will find the time I'll rewrite the metrics view for 1.4 anyway
