### ISSUE TITLE
springboot native 3.0.2 could not find the Template

### ISSUE THREAD

**Issue by 929541303** [codecentric/spring-boot-admin#2271]
springboot :  3.0.2
graalvm : OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)
` run jar    aot application `,  it works well.
<img width="1642" alt="image" src="https://user-images.githubusercontent.com/73211930/217408209-91718c91-0be6-47b3-8d3e-60638ebfcdf1.png">

**Comment by erikpetzold** [comment]
Hi @929541303, 
we assume you're trying to run your app as native image?

When building the native image, you have to provide runtime hints to the spring aot compiler, so he knows what will be used at runtime. See the official docs and tutoriuals for native image support in spring boot.

We're working on an example and runtime hints for spring boot admin, but this is not finished yet. See #2278

**Comment by 929541303** [comment]
来信收到，查看后会及时回复您！

**Comment by ulischulte** [comment]
Hi @929541303,

to avoid misunderstanding - since Chinese is not our mother tongue, could you please comment in tickets in English in the future?

There is a running sample which works with GraalVM and Native Image Builder in the current SNAPSHOT version of Spring Boot Admin:
https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet-graalvm

Does this example solve your problem?

Regards,
Uli

**Comment by 929541303** [comment]
来信收到，查看后会及时回复您！

**Comment by ulischulte** [comment]
Hi @929541303,

the current snapshot (3.0.4-SNAPSHOT) now includes autoconfigurations with RuntimeHints for SBA client and server running as Spring Boot 3 native applications. You can find a running GraalVM SBA server sample (+ self registration as a client) right here: https://github.com/codecentric/spring-boot-admin/tree/master/spring-boot-admin-samples/spring-boot-admin-sample-servlet-graalvm
This should solve your problem. If you encounter any other issues regarding GraalVM native support, feel free to open a new issue.

Regards,
Uli
