### ISSUE TITLE
Сustomization of the list of applications on the wallboard

### ISSUE THREAD

**Issue by dzahbarov** [codecentric/spring-boot-admin#2528]
I want to customize the list of services on the wallboard, which are shown to the user depending on some filter, for example, a filter that checks permissions. Currently ApplicationsController returns all the services that were found using the DiscoveryClient. Are there plans to add such functionality?

**Comment by erikpetzold** [comment]
Hi @dzahbarov 

this filtering would be on instance level (application is just a group of instances with the same name).

You could then provide your own InstanceFilter implementation that would be applied on InstanceRegistry and affect all views and interactions.

Is that what you want?

We would be happy to get a pull request. Otherwise we can implement that once someone has the time.

**Comment by SteKoe** [comment]
We have just polished your PR and merged the feature. It will be shipped in the next release. :)
