### ISSUE TITLE
question: is there a way to show missing instances?

### ISSUE THREAD

**Issue by guai** [codecentric/spring-boot-admin#2537]
Hi
Is it possible to provide SBA with a list of expected services so it could show them as missing or down even before they reached SBA on their start?
Or something similar
SBA provides a number of apps registered and I can see if it matches the expected number. But then it's not easy to figure out what actually is missing

**Comment by erikpetzold** [comment]
Hi @guai 

in general, SBA supports flexible and dynamic service landscapes, so there is no count or list of expected instances.

There are 2 ways how SBA knows about the monitored instances
1) applications register themselfes -> server knows who is there, but not who should be there
2) service discovery -> service gets list of services to monitor from infrastructure (service registry, kubernetes, ...)

For service discovery there is also a static way, where the server has a list of all clients to monitor (used INSTEAD of self registration): http://docs.spring-boot-admin.com/current/server.html -> SimpleDiscoveryClient
Maybe this solves your requirement.

**Comment by guai** [comment]
thanks, @erikpetzold it looks promising
