### ISSUE TITLE
charset error

### ISSUE THREAD

**Issue by Z-starts** [codecentric/spring-boot-admin#254]
![image](https://cloud.githubusercontent.com/assets/1948235/17885228/da6afcaa-694e-11e6-9155-cac323f2fc7e.png)

**Comment by joshiste** [comment]
could you provide a sample project for this?

**Comment by Z-starts** [comment]
just modify pom.xml with `
    <description>Spring Boot测试</description>`

**Comment by joshiste** [comment]
so you're using maven filtering to set  `spring.boot.application.name` ? Do you use a `application.properties` or `application.yml` file?

**Comment by joshiste** [comment]
When using your `UTF-8` characters in `application.yml` everything is correct. 

Using your characters in an `application.properties` on the other hand, the the name is displayed incorrect. This is due to spring boot loading `.properties`-files with `ISO-8859` as default charset (for more read here: https://github.com/spring-projects/spring-boot/issues/5361).

If there is no way around you for the `.properties`-file you need to use the unicode-escapes. `\u6d4b\u8bd5` in your case.

I'm closing this issue right now since this is not a problem of spring boot admin.
