### ISSUE TITLE
/heapdump  end point is not appearing

### ISSUE THREAD

**Issue by pradeepkusingh** [codecentric/spring-boot-admin#267]
I can see below tabs on admin GUI , thanks for your help to fix all issues. but /dump end point is missing.  

1- Metrics
2- logging
3- enviornment
4- JMX

Noticed that dump all thread dumps option is missing. I am using "1.4.1 version of admin UI". let me know if I need to upgrade to latest snapshots.

**Comment by joshiste** [comment]
Do you mean `/dump` (for threaddump) or `/heapdump` (for heapdumps)? As your text mentions both and is a bit confusing.

However the threads view (for `/dump`) is always visible. The heapdump link is only available when the client application has an accesible `/heapdump` endpoint - and therefore the client application must be at least spring boot 1.4.. 

If you have a look into your browsers' console you should notice a OPTIONS request to `/heapdump` this is how the ui figures out is the heapdumps are available, since the endpoint is sensitive by default, it could be possible that the request fails because of security.
