### ISSUE TITLE
application specific notifications

### ISSUE THREAD

**Issue by dominik42** [codecentric/spring-boot-admin#2743]
Is it possible, to configure application specific notifications?
I want to configure custom notifications for different client applications/ instances e.g. in order to configure application specific Slack channels. But as far as I can see (and use it some time) I can only configure notifications for all registers applications the same way.

**Comment by ulischulte** [comment]
Hi @dominik42,

You're right. Right now, only one notification webhook URL can be configured within an Admin server. You could still group messages differently within the configurable SpEl markup for specific clients by simply configuring slack notifications https://docs.spring-boot-admin.com/current/server-notifications.html#slack-notifications and combine those with a FilteringNotifier in order to delegate only to specific clients/instances/etc. (https://docs.spring-boot-admin.com/current/server-notifications.html#filtering-notifications).

I know it's just a workaround. As of now, all implemented Notifiers only support one 'topic'. 

The feature seems nice and not only a somewhat niche addition. If you want to contribute that feature, feel free ;) We would be happy to get a pull request. Otherwise we'll might implement it once someone has time.

Regards
Uli

**Comment by ulischulte** [comment]
Hi @dominik42,

a solution addressing your need to add specific Notifiers for different applications/teams etc. could also be the instantiation of several Notifiers in a Java Config (through autoconfiguration it's only possible to define one specific Notifier at a time).

Each bean should be a FilteringNotifier which delegates to a slack notifier and includes a custom filter (e.g. for filtering of tags etc.)


    @Bean
    public FilteringNotifier slackApp1Notifier(InstanceRepository repository, RestTemplate restTemplate) {
        SlackNotifier slackNotifier = new SlackNotifier(repository, restTemplate);
        slackNotifier.setChannel("team1");
        // ... set all necessary properties

        FilteringNotifier filteringNotifier = new FilteringNotifier(slackNotifier, repository);
        filteringNotifier.addFilter(new NotificationFilter() {

            @Override
            public String getId() {
                return "team 1 filter";
            }

            @Override
            public boolean filter(InstanceEvent event, Instance instance) {
                return instance.getTags().getValues().containsKey("team")
                        && instance.getTags().getValues().get("team").equals("1");
            }
        });

        return filteringNotifier;
    }
    

You now should add multiple of these beans - each with it's individual configuration.

Regards,
Uli

**Comment by ulischulte** [comment]
We're closing this issue due to missing feedback.
