### ISSUE TITLE
Admin security

### ISSUE THREAD

**Issue by redijedi** [codecentric/spring-boot-admin#283]
Is there any way to secure the application? Perhaps if it was integrated with spring security users could provide configurations for LDAP, etc?

**Comment by joshiste** [comment]
Duplikate of #279

**Comment by redijedi** [comment]
This shouldn't be closed because it is not a duplicate of the issue referenced. I am referring to securing this application, not the applications it talks to.

**Comment by steve-oakey** [comment]
You can secure it however you'd like, it's just a Spring Boot application.
You're embedding the server with @EnableAdminServer... you can still write
whatever security configuration code you want to suit your needs. Add
spring-boot-starter-security and you have Basic Auth out of the box, for
example.

- Steve

**Comment by joshiste** [comment]
But for the same reason: security solution are rather individual... OAuth
openId, LDAP, ...

If you had taken a look at the samples you would have noticed that they are
securing sba server as well... Since securing the clients and leaving the
server unsecured doesn't make sense at all.

Since the sba sever is just a simple spring web app just include spring
security and configure as you like...

**Comment by joshiste** [comment]
@steave-oakey sorry. Didn't saw your answer in my mails.
