### ISSUE TITLE
The client of Spring Boot used Netty, which resulted in the registered application not being visible on the server page

### ISSUE THREAD

**Issue by blankplace** [codecentric/spring-boot-admin#2902]
I am using version 2.5.1, which uses netty in the business system and introduces spring boot admin. However, I cannot see the registered application. It is amazing that when I remove netty, I can see the application instance

**Comment by ulischulte** [comment]
Hi @blankplace,

please always use the provided issue template in order to give us a better understanding of your problem.
Please fill out the missing information and provide a sample configuration or application if possible.

## Spring Boot Admin Server information

- **Version**:
  

- **Spring Boot version**:
  

- **Configured Security**:
  

- **Webflux or Servlet application**:
  

## Client information

- **Spring Boot versions**:
  

- **Used discovery mechanism**:
  

- **Webflux or Servlet application**:

**Comment by ulischulte** [comment]
We're closing this issue due to missing feedback.
