### ISSUE TITLE
Client host is not right displayed if running inside a docker container

### ISSUE THREAD

**Issue by grissomsh** [codecentric/spring-boot-admin#325]
A client running inside docker, the Boot admin server will display address like: http://8450c14378de:8090

**Comment by joshiste** [comment]
What would you expect?

**Comment by grissomsh** [comment]
The host name and port are both not correct from outside the docker container, thus the admin server could not access the API provided by client because of wrong endpoint.

But I could view the information of the client, so how could admin server access the information?

**Comment by joshiste** [comment]
The problem is that the container running the admin server cannot resolve the hostname of the client.

In this case you can set `spring.boot.admin.client.prefer-ip`, so the  client uses it's ip address to register at the admin, which should be reachable (if running on the same network).
Another way around this would need a DNS so that the admin container can resolve the hostname.
