### ISSUE TITLE
springcloud-config and admin not start in same project

### ISSUE THREAD

**Issue by Susuper2019** [codecentric/spring-boot-admin#3445]
## Spring Boot Admin Server information

- **Version**:2.7.2
  

- **Spring Boot version**:2.7.2
  

- **Configured Security**:
  

- **Webflux or Servlet application**: Servlet 
  

## Client information

- **Spring Boot versions**:2.7.2
  

- **Used discovery mechanism**: self registration
  

- **Webflux or Servlet application**: Servlet 
  

## Description
I'm working on a demo that simulates a config server and config client that uses location native. At this point I introduced admin, at this point I found that the UI of admin could not load correctly, and the admin client could not properly register to the server side. When I don't use config, everything works fine
![image](https://github.com/codecentric/spring-boot-admin/assets/53945022/90f59da3-3885-4355-9d0d-b99ff55c21f6)

**Comment by Susuper2019** [comment]
this is demo
https://github.com/Susuper2019/config-demo.git  
![image](https://github.com/codecentric/spring-boot-admin/assets/53945022/b7025698-445e-4afe-94f8-c4b57eb797df)
![image](https://github.com/codecentric/spring-boot-admin/assets/53945022/adac2df7-b654-4438-9d46-6572372a20ff)

**Comment by erikpetzold** [comment]
Hi @Susuper2019 

first: thanks for providing a demo, really helpful 👍 

As you can see in the first line in your first screenshot, the handler of the config server is answering all requests. Therefore it will handle the requests to the static resources and also the registration requests. This will fail.

A stated in https://docs.spring.io/spring-cloud-config/docs/current/reference/html/#_embedding_the_config_server it would be best to run both tools in separate applications.
Otherwise you need to set `spring.cloud.config.server.prefix` to make the config server only handle requests under this path.
