### ISSUE TITLE
Applications view rendering is slow

### ISSUE THREAD

**Issue by lidkowiak** [codecentric/spring-boot-admin#346]
I have about 280 instances of Spring Boot apps. Rendering of Applications view takes about  90 seconds, about 1400 requests are sent and the page is frozen during rendering. Most requests are sent to logfile, liquibase, flyway, heapdump actuator endpoints (in order to decide whether render corresponding view). In my case most apps are Spring Boot 1.2 based  so I get 404 for these endpoints.
I suggest following optimization: render flyway/liquibase/heapdump/logfile buttons and after click validate whether particular application handles selected feature/endpoint.
Additionally, have you considered combining info endpoints on the spring-boot-admin backend site?

**Comment by joshiste** [comment]
The requests are mades asynchronous and (in theory) shouldn't affect the rendering performance.

>I suggest following optimization: render flyway/liquibase/heapdump/logfile buttons and after click validate whether particular application handles selected feature/endpoint.

So you mean to check the endpoints after the user clicked the drop-down button? Good idea!
Additionally it would be good to solve #314 so that the not needed modules aren't loaded in the ui.

>Additionally, have you considered combining info endpoints on the spring-boot-admin backend site?

Not yet since the info isn't used on the backend. On the otherhand it would be nice to use them in the notifications...

**Comment by lidkowiak** [comment]
>  Additionally, have you considered combining info endpoints on the spring-boot-admin backend site?

I thought about following improvement: UI requests backend "please give me info for all registered applications" - one requests instead of hundreds in my case.

**Comment by joshiste** [comment]
Agreed please file another issue for that to keep things tracked seperate.

**Comment by joshiste** [comment]
Please test a 1.4.5-SNAPSHOT if things works now a bit better for you.

But this was only half of the rent. That many concurrent calls to `/info` are still a problem. 
I'll look if I can implement some kind of throttling in 1.4.5.

Aggregating the info on the server side won't make it into the 1.4.x branch, since implementing this heavily benefit from a99a889ab7723a00dc5ba7e4abfb82f79a5a26f9 which is in the master branch for 1.5.x.

**Comment by lidkowiak** [comment]
Thanks @joshiste! I will try test 1.4.5-SNAPSHOT.

**Comment by joshiste** [comment]
With the latest commit 34b2a071e8adfd407601040388e1827e423cd2a0 to the 1.4.x branch I could improve the rendering performance significantly. 300 applications now render in 2-3 seconds on my machine. Fetching all information for all applications does take longer but should not make the ui unusable. But that will be fixed with #349 hopefully.
