### ISSUE TITLE
Message tracking

### ISSUE THREAD

**Issue by baudo2048** [codecentric/spring-boot-admin#35]
Hi,
thanks for your work!!

Could you improve it adding incoming and outgoing rest messages? Something like spring remote shell do with /trace but adding the xml/json message bodies that pass through an endpoint.

How can I customize spring-boot-admin in order to do that?

**Comment by joshiste** [comment]
First you have to customize the spring-boot-acutators trace-endpoint to contain the message body.

To customize the spring-boot-admin-ui copy the spring-boot-admin-server-ui project and implement the presentation logic, build your own *-ui.jar and use this instead of ours.

(Or issue a pull request with the trace-endpoint-presentation, may be we will include it in future releases...)

**Comment by joshiste** [comment]
Added a view for the trace endpoint. For viewing the message content you have to customize spring-boot-actuators trace-endpoint yourself.
