### ISSUE TITLE
Jolokia not working with Docker

### ISSUE THREAD

**Issue by beanball** [codecentric/spring-boot-admin#352]
Jolokia works when I run the client application outside of Docker. When I register a client that is running from Docker (with service-url set), health works but nothing else.

Here is the result from /routes:

```json
{"/api/applications/7766ffe2/health/**":"http://my-app-url/health","/api/applications/7766ffe2/env/**":"http://a0a6c160a112:8080/env","/api/applications/7766ffe2/metrics/**":"http://a0a6c160a112:8080/metrics","/api/applications/7766ffe2/trace/**":"http://a0a6c160a112:8080/trace","/api/applications/7766ffe2/dump/**":"http://a0a6c160a112:8080/dump","/api/applications/7766ffe2/jolokia/**":"http://a0a6c160a112:8080/jolokia","/api/applications/7766ffe2/info/**":"http://a0a6c160a112:8080/info","/api/applications/7766ffe2/logfile/**":"http://a0a6c160a112:8080/logfile","/api/applications/7766ffe2/refresh/**":"http://a0a6c160a112:8080/refresh","/api/applications/7766ffe2/flyway/**":"http://a0a6c160a112:8080/flyway","/api/applications/7766ffe2/liquibase/**":"http://a0a6c160a112:8080/liquibase","/api/applications/7766ffe2/heapdump/**":"http://a0a6c160a112:8080/heapdump"}
```
The error log says : "java.net.UnknownHostException: a0a6c160a112: unknown error"

I didn't see anything in the documentation for modifying the URL for Jolokia. It seems to be using a url reported by Docker which was a problem I had with the health checks before modifying the service-url setting.

Edit:
This is what Jolokia reports in the browser:
```json
{"request":{"type":"version"},"value":{"agent":"1.3.5","protocol":"7.2","config":{"agentId":"172.22.0.2-1-727eb8cb-servlet","agentType":"servlet"},"info":{"product":"tomcat","vendor":"Apache","version":"8.5.6"}},"timestamp":1480968243,"status":200}
```

Spring Boot 1.4.2
Spring Boot Admin 1.4.4

**Comment by joshiste** [comment]
The problem is that the hostname of the client isn't visible to the admin server in docker. Because one container is started before the other they can't see each others hostnames via `/etc/hosts`.
A simple solution would be sticking to ip addresses instead, a complex solution would be to setup DNS for the docker hostnames.

In case you are using the spring boot admin client and a fat-jar deployment you just need to set `spring.boot.admin.client.prefer-ip=true` for using the ip addresses.
