### ISSUE TITLE
Spring Configuration Server + Keycloak Integration

### ISSUE THREAD

**Issue by TheSentinel454** [codecentric/spring-boot-admin#390]
Have you guys ever setup Spring Boot Admin backed by a Spring Cloud Configuration Server and used Keycloak for security?  Specifically, I'm trying to piece together a few different guides on integration, but have yet to get everything working properly.  I've got the Spring Boot Admin and Spring Cloud Configuration Server working together, but I'm having issues figuring out how to add security to both the Spring Boot Admin and the Spring Cloud Configuration server via Keycloak.

I can provide an example, but was just curious if anyone has any experience with this.  I've used a combination of the following guides:

https://keycloak.gitbooks.io/securing-client-applications-guide/content/v/2.3/topics/oidc/java/spring-security-adapter.html
https://github.com/codecentric/spring-boot-admin/commit/2a26043876c80312995e378ff9ff4f380d28225a

Thanks!

**Comment by joshiste** [comment]
Did you have a look at the current sba 1.50-SNAPSHOT and it's samples? It now has a story for security included, also have a look at the according [docs](http://codecentric.github.io/spring-boot-admin/1.5.0-SNAPSHOT/#securing-spring-boot-admin).
IIRC there are several ways on using keycloack (oauth, jwt, servlet filter) but since sba is a "simple" webapp all should do it. I've also setup some (older) examples in https://github.com/joshiste/spring-boot-admin-samples on how to integrate different security solutions (but none using keycloak)...
