### ISSUE TITLE
SBA cannot compose correct health check url

### ISSUE THREAD

**Issue by xyq000** [codecentric/spring-boot-admin#543]
1. On the SBA client side which connect to a eureka server, set:
```
server.port=10001
server.context-path=/demo
management.port=10002
eureka.instance.metadataMap.management.port=${management.port}
```
In this case, the correct health endpoint url is: `HOST:10002/health`. However, log shows that SBA server tries to connect to `HOST:10002/demo/health` and only gets a 404 error.

What is strange is that the SBA server can visit other endpoints of the SBA client via correct urls. On the SBA server dashboard, the client's info is shown normally except that it is marked as 'DOWN'. 

2. On the SBA client side which connect to a eureka server, set:
```
server.port=10001
server.context-path=/demo
management.context-path=/manage
eureka.instance.metadataMap.management.context-path=${management.context-path}
```
In this case, the correct health endpoint url should be: `HOST:10001/demo/manage/health`. However, log shows that SBA server tries to connect to `HOST:10001/health`. Still, a 404 error is returned. The dashborad marks the SBA client as "DOWN" and display no info of it.

Spring boot version: 1.5.6
SBA version: 1.5.3

**Comment by joshiste** [comment]
When using Eureka Spring Boot Admin uses the EurekaServiceInstanceConverter to register the applications. This converter takes the healthCheckUrl from Eureka into account, that's why all other endpoints are working except for health. The healthCheckUrl is defaulted in [spring cloud netflix](https://github.com/spring-cloud/spring-cloud-netflix/blob/348c96bf13be1b55abbd617c34255ffeffb7cb9b/spring-cloud-netflix-eureka-client/src/main/java/org/springframework/cloud/netflix/eureka/EurekaClientAutoConfiguration.java#L124 ). Please check your eureka registry server if the correct url has been registered.

You can enforce SBA to ignore the healthCheckUrl by adding a `DefaultServiceInstanceConverter` explicitly to your SBA server, which ignores the healthCheckUrl.
