### ISSUE TITLE
Feature Request: Audit Log when configuration changed.

### ISSUE THREAD

**Issue by zense10827** [codecentric/spring-boot-admin#566]
Hi, I just want to share an idea.

It would be great if Spring Boot Admin has a feature to log when to configuration was changed. 
For example, if user A change logging level from "INFO" to "TRACE" the audit log will log something like, 

> User: A - Change ROOT Logging level from "INFO" to "TRACE"

or if user B change the datasource url in JMX tab it will log,

> User: B - change datasource url from "/datasource/PROD" to "/datasource/PILOT"

I come up with this idea because I concern about the security, even if I already implemented authentication but Boot Admin is very powerful. It can change many configurations from this site.

It will be helpful if we have feature to log when the configuration was changed. So, I can track the person who changed config and ask them to provide the reason.

Thanks.

**Comment by mrumpf** [comment]
We are approaching 150 microservices in our system soon. With the Spring Boot Admin server a user can easily change the configuration or the log level of any microservice in the system, although the user should only be able to do that for a small fraction of the 150 microservices. 
I know that SBA uses the Actuator endpoints of Spring Boot and adding an audit feature would not prevent someone from doing a curl against the Actuator endpoints directly, but having a central place in SBA where all write operations are logged would be a very convenient way to log any modifications at a central place.
* Override config values
* Change log levels
* Create thread dumps

**Comment by joshiste** [comment]
As stated before imho the audit log should be written by the client applications and not the server as the config can be changed without sba

**Comment by joshiste** [comment]
Also sba already has a view for showing audit events... It just not centralised...

**Comment by joshiste** [comment]
Is it just the wish to aggregate across all your applications? 
How do you approach this for your application audit log or logfile?

**Comment by mrumpf** [comment]
The centralization and the content of the audit logging is the idea here.
The Actuator audit logging provides "login auditing" events only (per default):
https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-auditing.html
We use an ELK stack for making all our log files searchable.

I see 2 possible solutions:
1. Add an auditing feature to SBA
** Con: This is not bullet proof because one could use curl to do modifications
** Pro: No additional software necessary to get an overview on all config events
2. Extend the auditing feature of Spring Actuator so that config changes, log level changes and thread dumps are written to the audit log.
** Con: This solution has the drawback that you need e.g. an ELK stack to collect all logs from all instances.
** Pro: It covers all invocations to the Spring Actuator endpoints, even the ones that do not get triggered by SBA

**Comment by joshiste** [comment]
FYI: With SBA 2.0 implementing this yourself has become a breeze:

```java
    @Bean
    public InstanceExchangeFilterFunction auditLog() {
        return (instance, request, next) -> {
            if (HttpMethod.POST.equals(request.method()) || HttpMethod.POST.equals(request.method())) {
                log.info("{} for {} on {}", request.method(), instance.getId(), request.url());
            }
            return next.exchange(request);
        };
    }
````

**Comment by alaaeddinezammel** [comment]
that with reactor what to do if we are using a synchrone app ?
