### ISSUE TITLE
SBA Clustering vis HazelCast on PaaS which does not support MultiCast protocol

### ISSUE THREAD

**Issue by dsushil2000** [codecentric/spring-boot-admin#615]
I am trying to work on the SBA clustering to provide scalability and fault-tolerance. I see section on clustering via HazelCast. I am running 4 node cluster in Openstack env. The Multicast protocol is disabled. The Only way to find nodes is via UniCast and IP. Can we use something like HazelCast integration with Eureka mentioned here:
https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/springboot-eureka-partition-groups
How to solve the problem with the Hazelcast configuration mentioned in the clustering section?

**Comment by joshiste** [comment]
I'm no expert for hazelcast, but I don't see why it shouldn't work.

**Comment by dsushil2000** [comment]
When you say Clustering; is SBA expecting the multiple nodes on same server?

**Comment by joshiste** [comment]
No.
The datastore is just switched to hazelcast and so all of hazelcast's replication mechanisms are supported. If you can't use multicast so that the hazelcast instances can find each other you need to use some other option (e.g. integrating eureka, or just use a list of fixed addresses to boostrap)
