### ISSUE TITLE
Add Admin Config for Actuator Https Scheme

### ISSUE THREAD

**Issue by forGitMeNotPlease** [codecentric/spring-boot-admin#656]
We run our apps in Kubernetes, so I use the discovery client to find pods in the cluster.  It worked wonderfully, until we had to make our communication from the NGINX load balancer to the pod HTTPS.  

I have added the following to the client applications:
`server.ssl.enabled=true`

So the clients are all behind https.

Now, I'm trying to get Spring Actuator enpoint working via calling it https as well. 

In `Spring Admin Server` I've added the following `client` config:

```
spring.boot.admin.client.metadata.management.port=8081
spring.boot.admin.client.metadata.management.ssl.enabled=true
```

I've also tried the same to the `discovery` config:
```
spring.boot.admin.discovery.metadata.management.port=8081
spring.boot.admin.discovery.metadata.management.ssl.enabled=true
```

Spring Boot Admin tried to connect to `http://192.168.183.43:443`.

I specified `ssl.enabled=true` expecting it to call `https://192.168.183.43:8081` because I've specified the port and ssl.  Instead, I see the following in the logs:

`ResourceAccessException: I/O error on GET request for "http://192.168.183.43:443/management/health"`

Why does it call to port `443`?  Why no scheme `https`?

**Comment by joshiste** [comment]
I'm a bit confused. Are you using the SBA client or a Spring Cloud DiscoveryClient? You really shouldn't use both.

1) There is no `spring.boot.admin.discovery.metadata.management.ssl.enabled` or `spring.boot.admin.discovery.metadata.management.ssl.enabled` property.

2) **In case you are using `spring-boot-admin-client`**
If you've set `management.port` you also need to use `management.ssl.enabled=true` and it should work out of the box.

3) **In case you are using some `DiscoveryClient`**
Make sure you configure the DiscoveryClient so that the application registers with the https scheme.
For eureka for example you need to configure `eureka.instance.securePortEnabled`.
