### ISSUE TITLE
Spring-boot-admin- email alert notification for JVM memmory issues

### ISSUE THREAD

**Issue by aravind3747** [codecentric/spring-boot-admin#695]
Hello,
I have situation that when ever my java spring boot application reaches maximum heap memory my application is fails to respond so,
I am wondering that  is spring boot admin has a capability to send email notifications if my application reaches maximum java heap memory?  

if yes please suggest necessary configuration.

Thanks, 

i am able to get the emails alerts if my application goes down/up or unknown

**Comment by joshiste** [comment]
If your application stops responding the health-check should be triggered with the current implementation.

It's totally normal for applications to reach max heap - the problem is that it stays at max and gc is burning cpu. This is a rather difficult problem. In [spring-boot#6988](https://github.com/spring-projects/spring-boot/pull/6988) a memory health indicator is proposed. This is in my opinion the way to go.

**Comment by suresh447** [comment]
Hi Aravind,

You mentioned you can able to send email notification when the application is down. can you please help me in how to set email alerts for when ever the application is down.
