### ISSUE TITLE
Improvements for the Details Page in 2.0

### ISSUE THREAD

**Issue by matthjes** [codecentric/spring-boot-admin#697]
Hi,

I don't want to offend anyone, but I'm somehow disappointed in the new UI (Version 2.0.0-SNAPSHOT). It's very confusing and the layout is not the best. (If this is just a problem with my installation, then ignore this issue).

For example:
![2018-04-06 14_25_38-spring boot admin](https://user-images.githubusercontent.com/1440866/38421284-ea1ce972-39a6-11e8-82aa-abcd399a704c.png)
Here a lot of space is wasted with empty table rows or huge margins. All those table border lines don't look so good.

Also, showing the status of health indicators could be more prominent, the little tick marks aren't very visible.

Another example:
![2018-04-06 14_28_35-spring boot admin](https://user-images.githubusercontent.com/1440866/38421355-231dad42-39a7-11e8-8ff5-11e1ed426817.png)
The cards are all over the place, some are aligned, other are not.

Overall, the look is not bad, but at some points too "lightweight" (in my opinion).

**Comment by joshiste** [comment]
@matthjes Thanks for you feedback.
For the health section I agree without that the current layout wastes space.
IIRC the cards in the old ui are also sometimes not well aligned. In your example they should align if the error messages disappears... The error message is caused by trying to fetch the systemload - which is not available on all platforms (as in your case) so we should fix that.
I'll have once more a look at the css and try to fix this.

p.s. I hope you like the new ui in general despite the detail page, as there are lot of enhancements and new stuff on the other pages...

**Comment by matthjes** [comment]
In general I like the new UI, it looks more modern than the older one :) I think the issues I mentioned are minor compared to the improvements.

**Comment by joshiste** [comment]
I've made some changes to the health section. It now looks like this:
![image](https://user-images.githubusercontent.com/8779225/38639621-169e394a-3dd2-11e8-8368-8d2fbd029f49.png)
