### ISSUE TITLE
Allow the UI to be served under a different context path

### ISSUE THREAD

**Issue by mrumpf** [codecentric/spring-boot-admin#81]
For testing we wanted to package the Eureka Server, the Spring Cloud Config Server and the Spring Boot Admin UI into one war file.
When adding all the necessary dependencies and the applying the annotations to the Spring Boot Application class, neither the Eureka Dashboard, nor the Admin Server Dashboard find their web ressources (CSS, JS, IMG).
It would be great if you could change the `targetPath` in the pom.xml of the admin server ui project to be `META-INF/resources/admin/` so that the Admin UI becomes available under the `/admin` context path and thus does not clash with the Eureka Server Dashboard.
Setting the `server.contextPath` does not work as it also moves the Eureka Dashbaord to the new context path.

**Comment by joshiste** [comment]
I wonder if it is really reasonable putting all the three into one single app. Every one has it's own responsibility (service discovery, configuration, monitoring) in terms of microservices you really should keep 'em separated.

This is not a quite easy task, since not only the static resources has to be served under a different context path, but also the REST-api. 
Making the Controller & ResourceHandler configurable will unnecessarily bloat the code.

**Comment by joshiste** [comment]
p.s. does the Eureka Server Dashboard allow to alter the url?

**Comment by mrumpf** [comment]
OK, I understand. We separated the Admin UI & the Hystrix Dashboard from the Eureka and Config server now.
p.s. You can set the `server.contextPath`, but that moves all applications to a new context path.
