### ISSUE TITLE
login with configured context-path 

### ISSUE THREAD

**Issue by altfatterz** [codecentric/spring-boot-admin#835]
When I configure the context-path after login in it does not redirect to the 
`host:port/context-path` instead it stays at `host:port`

An example project is here:
https://github.com/altfatterz/spring-boot-admin

Using the following config:
```yaml
spring:
  security:
    user:
      name: admin
      password: admin
  boot:
    admin:
      context-path: /admin
```

And security configuration

```java
@Configuration
class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    private final String adminContextPath;

    public WebSecurityConfig(AdminServerProperties adminServerProperties) {
        this.adminContextPath = adminServerProperties.getContextPath();
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        SavedRequestAwareAuthenticationSuccessHandler successHandler = new SavedRequestAwareAuthenticationSuccessHandler();
        successHandler.setTargetUrlParameter("redirectTo");

        http.authorizeRequests()
                .antMatchers(adminContextPath + "/assets/**").permitAll()
                .antMatchers(adminContextPath + "/login").permitAll()
                    .anyRequest().authenticated()
                .and()
                    .formLogin().loginPage(adminContextPath + "/login").successHandler(successHandler).and()
                    .logout().logoutUrl(adminContextPath + "/logout").and()
                    .httpBasic()
                .and()
                    .csrf().disable();
    }
}
```

**Comment by joshiste** [comment]
Thanks for providing the sample project!
This is primarily not a Spring Boot Admin issue, but as it's the code from the sample/docs I did take a look at it. The problem is the Spring Security configuration. You need to set the `defaultTarget` url via `successHandler.setDefaultTargetUrl(adminContextPath + "/");`

I've updated the samples

**Comment by altfatterz** [comment]
Great! Thanks.

**Comment by hosseinjk** [comment]
The problem is solved by the following method:
The first:
#set address site and port
server.port=8081
server.servlet.context-path=/adminPanel

The second:
#controller
 @GetMapping("/login")
    public String showLoginForm(Model model) {
        Authentication authentication = SecurityContextHolder.getContext().getAuthentication();
        if (authentication == null || authentication instanceof AnonymousAuthenticationToken) {
            return "login";
        }
        return "redirect:/home";
    }

The third :
#You must enter the default address for sending data here:
#server.servlet.context-path=/adminPanel
<form class="form-signin" action="/adminPanel/login" method="post">
<h2 class="form-signin-heading">Please sign in</h2>
<div class="form-group">
<label for="username" class="sr-only">Username</label> <input
type="text" class="form-control" placeholder="Username"
name="username" id="username" required="required"
autofocus="autofocus" />
</div>
<div class="form-group">
<label for="password" class="sr-only">Password</label> <input
type="password" class="form-control" placeholder="Password"
name="password" id="password" required="required" />
</div>
<button class="btn btn-lg btn-primary btn-block" type="submit">Sign In</button>		</form>

The fourth :
#in Method WebSecurityConfig:
 @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                .formLogin()
                .failureUrl("/login?error")
                .defaultSuccessUrl("/home")
                .loginPage("/login")
                .usernameParameter("email")
                .permitAll()
                .and()
                .logout().permitAll().logoutUrl("/logout").logoutSuccessUrl("/login")
                .and()
                .csrf().disable();
    }

Your login is working properly
