### ISSUE TITLE
Use more informations from Eureka DiscoveryClient

### ISSUE THREAD

**Issue by lidkowiak** [codecentric/spring-boot-admin#94]
When set `management.port spring-boot-admin` is not able to construct valid management URL. The same situation is when `server.context-path` is set (please see: http://stackoverflow.com/questions/32136490/spring-boot-actuator-enpoints-with-set-server-context-path)
Have you submitted this issue to Spring Cloud team?
Maybe a point of extension in `de.codecentric.boot.admin.discovery.ApplicationDiscoveryListener` as strategy pattern to construct `de.codecentric.boot.admin.model.Application` based on `org.springframework.cloud.client.ServiceInstance` would be acceptable solution?

**Comment by joshiste** [comment]
Does this only apply when using the DiscoveryClient or even when using the spring-boot-admin-starter-client?

**Comment by steve-oakey** [comment]
DiscoveryClient only. I investigated this a while ago and a possible
solution (other than adding more fields to a ServiceInstance in Spring
Cloud) is to use the Eureka DiscoveryClient directly (instead of the Spring
Cloud wrapper). You can get much more data from this (including the generic
metadata map which you could use to require a field for "managementPath".

There is an issue in Spring Cloud I believe to add more fields to
ServiceInstance, I can't recall the issue number since I am replying via
email on mobile,

-Steve

**Comment by joshiste** [comment]
As in #111 mention the healthCheckUrl should be also taken in account

**Comment by drissamri** [comment]
Is there any workaround for this currently?

**Comment by sfat** [comment]
@drissamri I've tried in different ways using only Eureka server or modifying spring-boot-admin to override different beans, but I ended using plain spring-booot-admin because it's simpler that way.

**Comment by joshiste** [comment]
In a first step I made the ApplicationDiscoeryListener customizable, so in future It should be easier to exchange the behaviour,

**Comment by jvmlet** [comment]
#159 should fix this issue

**Comment by joshiste** [comment]
closed in favour of #154
